# Generated by Django 2.2 on 2019-12-11 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='question_images')),
                ('votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='answer_images')),
                ('votes', models.IntegerField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna_app.QuestionModel')),
            ],
        ),
    ]
