# Generated by Django 2.2 on 2019-12-13 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qna_app', '0004_categorymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='qna_app.CategoryModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
