# Generated by Django 2.2 on 2019-12-13 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qna_app', '0005_auto_20191213_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='qna_app.CategoryModel'),
        ),
    ]
