# Generated by Django 2.2 on 2019-12-13 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna_app', '0006_auto_20191213_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='is_answered',
        ),
    ]
