# Generated by Django 2.2 on 2019-12-13 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna_app', '0007_auto_20191213_0359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryModel',
        ),
    ]
