# Generated by Django 2.2 on 2019-12-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna_app', '0009_auto_20191213_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('reputation', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
