# Generated by Django 2.2 on 2019-12-13 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qna_app', '0010_usermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='answermodel',
            name='user',
            field=models.ForeignKey(default='23', on_delete=django.db.models.deletion.CASCADE, to='qna_app.UserModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='user',
            field=models.ForeignKey(default='23', on_delete=django.db.models.deletion.CASCADE, to='qna_app.UserModel'),
            preserve_default=False,
        ),
    ]
